site_name: actions-test-004
site_description: 
repo_url: https://github.com/rhdh-skitamura-org/actions-test-004-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - actions-test-004 Documentation: index.md
